/**
 * @fileoverview Public exports for @buildaureon/sdk.
 *
 * Import from `@buildaureon/sdk` in utility apps, scripts, and integrations.
 */

export {
  AureonClient,
  createAureonClient,
  createLocalAureonClient,
  type AuthMeResponse,
  type AuthNonceResponse,
  type AuthSessionResponse,
  type SyncPortfolioResult,
  type DeveloperApiKey,
  type CreatedDeveloperApiKey,
} from "./client/index.js";

export {
  createSessionTokenProvider,
  type SessionTokenProvider,
} from "./auth/index.js";

export {
  AureonConflictError,
  AureonError,
  AureonNetworkError,
  AureonNotFoundError,
  AureonTimeoutError,
  AureonValidationError,
  errorFromHttpStatus,
  isAureonError,
  type AureonErrorCode,
} from "./errors/index.js";

export {
  buildPolicySummary,
  normalizeCreateObjectiveInput,
  normalizeUpdateObjectiveInput,
  assertValidExecutionReceipt,
  isValidExecutionReceipt,
  validateExecutionReceipt,
  validateSettlementRecord,
  type ReceiptValidationCode,
  type ReceiptValidationIssue,
  type ReceiptValidationResult,
} from "./validation/index.js";

export {
  formatUsd,
  formatWeight,
  healthTone,
  formatSignedPercent,
  formatIsoTime,
  buildAllocationComparison,
  detectPlanParadox,
  type AllocationComparisonRow,
  type PlanParadoxResult,
  buildObjectivePortfolioFlow,
  parseFinancialIntent,
  resolveObjectiveFromIntent,
  type FinancialIntent,
  type ObjectivePortfolioFlow,
  buildDriftRestoreFlow,
  buildDriftRestoreFlowFromSnapshot,
  inferDriftPhase,
  type DriftRestoreFlow,
  type DriftRestorePhase,
  buildReceiptVerificationFlow,
  inferProofTier,
  type ReceiptVerificationFlow,
  type ReceiptVerificationPhase,
  type ReceiptProofTier,
  buildPortfolioWatchFlow,
  buildPortfolioWatchFlowFromSnapshot,
  buildPortfolioWatchBriefingLines,
  inferPortfolioWatchPhase,
  DEFAULT_PORTFOLIO_WATCH_BRIEF,
  type AgentHost,
  type PortfolioWatchFlow,
  type PortfolioWatchPhase,
  buildFullAureonLoopFlow,
  buildFullAureonLoopFlowFromSnapshot,
  inferFullAureonLoopPhase,
  DEFAULT_FULL_LOOP_BRIEF,
  type FullAureonLoopFlow,
  type FullAureonLoopPhase,
  buildFinancialAuditTrail,
  formatAuditTrailLines,
  type AuditTrailGap,
  type AuditTrailGapCode,
  type AuditTrailReceiptRow,
  type FinancialAuditTrail,
} from "./formatting/index.js";

export type {
  ApplyMarketEventInput,
  AureonClientOptions,
  CreateObjectiveInput,
  DashboardOverview,
  ExecutionReceipt,
  RestorePlan,
  RestorePlanKind,
  SettlementRecord,
  SettlementStatus,
  ExecutionSettlementLookup,
  RegistryStatus,
  RegistryRef,
  ObjectiveRegistryRecord,
  PrepareRegistryResult,
  ObjectiveRegistryLookup,
  HealthState,
  MarketEvent,
  MarketPreset,
  Objective,
  ObjectiveHealth,
  ObjectiveKind,
  ObjectivePolicy,
  ObjectivePriority,
  ObjectiveAutomationMode,
  ObjectiveStatus,
  PortfolioPosition,
  PortfolioPositionInput,
  PortfolioSnapshot,
  RestoreSuggestion,
  RestoreSuggestionAction,
  TimelineEvent,
  TimelineEventType,
  UpdateObjectiveInput,
  WatchdogAlertResult,
  WatchdogRefreshResult,
  MarkQuote,
  MarkQuoteSource,
  VaultBalance,
  VaultDepositSymbol,
  VaultOverview,
  VaultPrepareResult,
  VaultPreparedStep,
  VaultStatus,
  VaultToken,
  VaultWithdrawSymbol,
} from "./types/index.js";

export {
  OBJECTIVE_KINDS,
  OBJECTIVE_PRIORITIES,
  isObjectiveKind,
  isObjectivePriority,
  isHealthState,
  isVaultSettlement,
  isChainVerifiedReceipt,
  formatReceiptSummary,
  formatSettlementSummary,
  findTimelineEventsForReceipt,
  pickWorstHealth,
  TIMELINE_EVENT_TYPES,
  isTimelineEventType,
} from "./types/index.js";

export { assertBaseUrl, joinUrl, requestJson, withQuery } from "./transport/index.js";

export {
  DEFAULT_API_BASE_URL,
  LOCAL_API_BASE_URL,
  API_KEY_HEADER,
  DEFAULT_TIMEOUT_MS,
  PRODUCT_NAME,
  PRODUCT_TAGLINE,
  SDK_NAME,
  SDK_VERSION,
  ENDPOINTS,
} from "./constants/index.js";

export {
  createConsoleLogger,
  silentLogger,
  resolveFetch,
} from "./adapters/index.js";
